### Register user baru
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "name": "Budi Owner",
  "email": "budi@barbershop.com",
  "password": "password123",
  "tenantSlug": "barbershop-budi"
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "budi@barbershop.com",
  "password": "password123",
  "tenantSlug": "barbershop-budi"
}

### Login salah password (harusnya 401)
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "budi@barbershop.com",
  "password": "salah",
  "tenantSlug": "barbershop-budi"
}